title: Sylwia Budzynska a.k.a. BlazingWind
author: Sylwia Budzynska
description: > # this means to ignore newlines until "baseurl:"
  Sylwia Budzynska a.k.a. BlazingWind


# social links
twitter_username: BlazingWindSec # DO NOT include the @ character, or else the build will fail!
github_username:  BlazingWind # DO NOT include the @ character, or else the build will fail!
theme: minima
show_excerpts: true # set to false to remove excerpts on the homepage
